### ISSUE TITLE
Crustashe vs Teeplate

### ISSUE THREAD

**Issue by drujensen** [TechMagister/kemalyst-generator#15]
@TechMagister I saw you decided to go with Teeplate.  I think it's cleaner but I don't know how we will be able to create the `ecr`'s for views.

Any suggestions?

**Comment by drujensen** [comment]
One option is to generate slang templates instead.  https://github.com/jeromegn/slang

What do you think?

**Comment by TechMagister** [comment]
It would be great to handle multiple templates engines, because slim is a good template language but the syntax is very different from the others ( liquid, ecr, mustache, ... )

Why not using slang (slim) by default, but in my opinion, it's necessary to, at least, be able to generate templates for each engine supported by kilt.

**Comment by drujensen** [comment]
👍 maybe we can convert slang to ecr in a post process if `-t ecr` is passed in as a parameter.
