### ISSUE TITLE
Model generator use .kgen.yml vs config/database.yml

### ISSUE THREAD

**Issue by drujensen** [TechMagister/kemalyst-generator#40]
@elorest question for you. 

The `init` app now generates a `.kgen.yml` file to keep track of what options they selected when they created the app.  This includes the `type`, `database` and template `language`.

Should the generator for the models look at the `config/database.yml` to determine the database or should it pull from the `.kgen.yml`?

fyi, I included the `type` of project so we can add `kgen init api [name]` and adjust the generators appropriately.

**Comment by elorest** [comment]
Probably the database.yml since you might want change database and
adjusting in 2 places would be annoying. It also seems to me that people
might want to generate both web and api controllers in a single project so perhaps we should just use the .kgen.yml to check for defaults but then let them override it with an option when generating scaffolding/controllers.

**Comment by drujensen** [comment]
yeah, that makes since.  I agree, we can provide an override in the generators to specify the project type, database and template language in case they want to mix-match.
